name: 🚀 Request Project Listing on audius.community
description: Submit your project to be featured on audius.community
title: "Listing Request: [Your Project Name]"
labels: [submission, listing-request]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in getting listed on **audius.community**!

        Fill out the details below so we can learn more about your project and consider it for inclusion.

        Criteria:
        * Project must be open source
        * Project must be built on the Audius protocol
        * Show developer badges where possible

  - type: input
    id: project-name
    attributes:
      label: 🔤 Project Name
      description: What's the name of your project?
      placeholder: e.g. AudiusPlayer
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: 📄 Project Description
      description: Tell the community briefly what your project does and who it's for.
      placeholder: A lightweight Audius music player built for desktop.
    validations:
      required: true

  - type: input
    id: project-url
    attributes:
      label: 🌐 Project Website or Demo URL
      description: Share a link to your live project or demo.
      placeholder: https://yourprojecturl.com
    validations:
      required: true

  - type: input
    id: github-url
    attributes:
      label: 🐙 GitHub Repository
      description: Provide the link to your GitHub repo.
      placeholder: https://github.com/yourname/yourproject
    validations:
      required: true

  - type: dropdown
    id: subdomain-request
    attributes:
      label: 🌍 Would you like hosting on a subdomain of audius.community?
      description: Select "Yes" if you want your project accessible at `yourproject.audius.community`
      options:
        - "No"
        - "Yes - I’ll need a redirect"
        - "Yes - I have a static frontend"
        - "Yes - It’s compatible with Cloudflare Workers"
    validations:
      required: true

  - type: textarea
    id: hosting-details
    attributes:
      label: 🛠️ Hosting Details (if yes)
      description: If you're requesting a subdomain or redirect, explain how your app is hosted or provide deployment instructions. If you would like a specific subdomain name, please specify. Otherwise, your project name will be used.
      placeholder: My app is deployed as a static site on Vercel and can be served via a redirect on audius.community.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Ty 🫡. Let's build the future of music together. 🎧
